[package]
name = "sylvie"
description = "VARIANT support for Rust. Clean, idiomatic handling of WinAPI/COM results."
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Tom Niget <niget.tom@gmail.com>"]
repository = "https://github.com/zdimension/sylvie"
categories = ["data-structures"]
keywords = ["com", "windows", "variant", "winapi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
derivative = "2.2.0"
enumn = "0.1.3"
rust_decimal = "1.22.0"
widestring = "0.5.1"
winapi = { version = "0.3.9", features = ["oaidl"] }
