name: PR

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/toolchain@v1

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
